version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
    # For hot reloading
    volumes:
      - ./:/usr/src/app

  db:
    image: postgres
    restart: always
    ports:
      - "5001:5432"
    volumes:
        - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=autoapidb
volumes:
  db_data:
